config/routes.rb
Galleryconnect::Application.routes.draw do
    resources :users do 
    resources :cards
    resources :webcards, only: [:index, :show]
  end

  resources :webcards

  get '/session', to: 'session#new'
  post '/session', to: 'session#create'
  delete '/session', to: 'session#destroy'

  root 'welcome#index'
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :user

  def self.hellotext
    print "hello Nick"
  end

  def self.send_weekly_cards
    @allcards = Card.all
    @allcards.each do |card|
      if !card.called?
        UserMailer.weekly_cards(card).deliver
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cards

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  self.has_secure_password()

  def is_admin?
    email == "nicholasjaybundy@gmail.com" || "heieunjun@gmail.com" || "jen@gallerychurch.com"
  end

end

app/models/webcard.rb
class Webcard < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  helper_method :current_user, :logged_in?
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :load_user
  before_action :load_cards, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.is_admin?
    @allcards = Card.all
    else
      redirect_to user_path(current_user.id)
    end
  end

  def new
    @users = User.all
    @card = Card.new
  end

  def create
    @connectioncard = Card.new(card_params)
    
    if @connectioncard.save
      UserMailer.send_connection(@connectioncard.user_id, @connectioncard).deliver
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def update
    @changed = @cards.update(card_params)

    if @changed
      redirect_to user_path(@user.id)
    else
      flash[:message] = 'Update Failed!'
      redirect_to user_path(@user.id)
    end

  end

  def destroy
    @cards.destroy
    redirect_to user_cards_path(@user)
  end

  private

  def load_user
    @user = User.find(params[:user_id])
  end

  def load_cards
    @cards = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:first_name, :last_name, :phone, :email, :address, :city, :state, :zipcode, :prayer, :notes, :called, :user_id) 
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def index
  end

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    
    if user && (user.authenticate(params[:password]))
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:message] = "Username or Password not found!"
      redirect_to root_path
    end 

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :authorize, only: [:edit, :show]


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
    
  end

  def show
    @cards = Card.where(user_id: @user)
    @allcards = Card.all
    render :show
  end

  def edit
    render :edit
  end

  def update
    @changed = @user.update(user_params)

    if @changed
      redirect_to user_path(@user.id)
    else
      render :edit
    end

  end

  def destroy
    @user.destroy
    redirect_to users_path(@user)
  end


  private

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :street_address, :city, :state, :zipcode, :password, :password_confirmation)
  end

  def authenticate
    unless logged_in?
      redirect_to root_path
    end
  end

  def authorize
    unless current_user == @user
      redirect_to root_path
    end
  end

end

app/controllers/webcards_controller.rb
class WebcardsController < ApplicationController
  before_action :load_user, only: [:index, :show]
  before_action :load_webcard, only: [:show, :destroy]

  def index
    @allwebcards = Webcard.all
  end

  def new
    @card = Webcard.new
  end

  def create
    @webcard = Webcard.new(card_params)
    
    if @webcard.save
      UserMailer.new_webcard_notification(@webcard).deliver
      redirect_to "http://www.gallerychurch.com/new"
    else
      render :new
    end
  end

  def show
    @webcard = Card.new
    @users = User.all
  end

  def destroy
    @wcard.destroy
    redirect_to user_webcards_path(current_user)
  end

private

  def card_params
    params.require(:webcard).permit(:first_name, :last_name, :phone, :email, :address, :city, :state, :zipcode, :prayer, :notes, :called, :user_id) 
  end

  def load_webcard
    @wcard = Webcard.find(params[:id])
  end

  def load_user
    @user = User.find(params[:user_id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :logged_in?

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_left.html.erb
 <div class='new-card-form'>
      <%= @form.text_field :first_name %>
      <%= @form.label "First Name" %><br /><hr />
      <%= @form.text_field :last_name %>
      <%= @form.label "Last Name" %><br /><hr />
      <%= @form.email_field :email %>
      <%= @form.label "Email" %><br /><hr />
      <%= @form.text_field :phone %>
      <%= @form.label "Phone" %><br /><hr />
      <%= @form.text_field :address %>
      <%= @form.label :address %><br /><hr />
      <%= @form.text_field :city %>
      <%= @form.label :city %><br /><hr />
      <%= @form.text_field :state %>
      <%= @form.label :state %><br /><hr />
      <%= @form.text_field :zipcode %>
      <%= @form.label :zipcode %><br /><hr />
      <%= @form.text_area :prayer, :rows=>"3", :cols=>"35"%>
      <%= @form.label "Prayer Request" %><br /><hr />
      <%= @form.text_area :notes, :rows=>"3", :cols=>"35" %>
      <%= @form.label "notes" %><br /><hr />
  </div>

app/views/cards/index.html.erb
<div class="user-page-container">
  <div class="connect-image">
    <%= image_tag('GC.png') %>
  </div>
  <hr />
  <div class="user-title">
    <p>All Cards</p>
  </div>
  <div class="contact-buttons">
    <div id="uncontacted">Not Contacted</div><div id="contacted">Contacted</div>
  </div>
<% if @user.is_admin? %>
  <div id="uncontacted-card-holder">
    <% @allcards.each do |card| %>
    <% unless card.called? %>
    <div class="assigned-cards">
      <form action="<%= user_card_path(@user.id, card.id) %>" method="POST" class="delete-card">
                <input type="hidden" name="_method" value="DELETE" />
                <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
                <button class='deletebutton'>Delete Card x</button><br />
      </form>       
      <p>Name: <%= card.first_name + " " + card.last_name%></p><hr />
      <p>Phone: <%= card.phone %></p><hr />
      <p>Email: <%= card.email %></p><hr />
      <p>Address:<br /> <%= card.address %><br /><%= card.city + ", " + card.state %><br /><%= card.zipcode %></p><hr />
      <p>Prayer: <%= card.prayer %></p><hr />
      <p>Notes: <%= card.notes %></p>
      <% if card.called? == false %>
      <p>Called: <span>Has Not Been Called</span></p>
      <% else %>
      <p>Called: Has Been Called</p>
      <% end %>
    </div>
    <% end %>
    <% end %>
  </div>
  <div id="contacted-card-holder">
    <% @allcards.each do |card| %>
    <% if card.called? %>
    <div class="assigned-cards">
      <form action="<%= user_card_path(@user.id, card.id) %>" method="POST" class="delete-card">
                <input type="hidden" name="_method" value="DELETE" />
                <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
                <button class='deletebutton'>Delete Card x</button><br />
      </form>   
      <p>Assigned To: <%= User.where(id: card.user_id).first.first_name %></p><hr />      
      <p>Name: <%= card.first_name + " " + card.last_name%></p><hr />
      <p>Phone: <%= card.phone %></p><hr />
      <p>Email: <%= card.email %></p><hr />
      <p>Address:<br /> <%= card.address %><br /><%= card.city + ", " + card.state %><br /><%= card.zipcode %></p><hr />
      <p>Prayer: <%= card.prayer %></p><hr />
      <p>Notes: <%= card.notes %></p>
      <% if card.called? == false %>
      <p>Called: <span>Has Not Been Called</span></p>
      <% else %>
      <p>Called: Has Been Called</p>
      <% end %>
    </div>
    <% end %>
    <% end %>
  </div>
  <% end %>
</div>

<script>
  $('#contacted').click(function(){
    $('#contacted-card-holder').show(function(){
      $('#uncontacted-card-holder').hide();
    });
  });

  $('#uncontacted').click(function(){
    $('#contacted-card-holder').hide(function(){
      $('#uncontacted-card-holder').show();
    });
  });
</script>

app/views/cards/new.html.erb
<div class="user-page-container">
  <div class="connect-image">
    <%= image_tag('GC.png') %>
  </div>
  <hr />
    <%= form_for [@user, @card] do |f|%>
      <% @form = f %>
      <%= render "left" %>
      <%= render "right" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galleryconnect</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="links">
      <%= link_to "Home", user_path(current_user.id), class: "logout" unless session["user_id"].nil? %> 
      <%= link_to "Log Out", "/session", method: "delete", class: "logout" unless session[:user_id].nil? %>
      <% if session[:user_id] && current_user.is_admin? %>
      <%= link_to "New Card", new_user_card_path(current_user.id), class: "logout" unless session[:user_id].nil? %>
      <% end %>
  </div>
    <% if session[:user_id] && current_user.is_admin? %>
      <div id="links">
        <%= link_to "All Users", users_path(current_user.id), class: "logout" unless session[:user_id].nil? %>
        <%= link_to "All Cards", user_cards_path(current_user.id), class: "logout" unless session[:user_id].nil? %>
        <%= link_to "Web Cards", user_webcards_path(current_user.id), class: "logout" unless session[:user_id].nil? %>
      </div>
    <% end %>
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<div class="user-page-container">
  <div class="connect-image">
    <%= image_tag('GC.png') %>
  </div>
  <hr />
  <div class="user-title">
    <p>All Users</p>
  </div>
<% if current_user.is_admin? %>
  <div class="card-holder">
    <% @users.each do |user| %>
    <div class="assigned-cards">
      <form action="<%= user_path(user.id) %>" method="POST" class="delete-card">
                <input type="hidden" name="_method" value="DELETE" />
                <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
                <button class='deletebutton'>Delete User x</button><br />
      </form>         
      <p>Name: <%= user.first_name + " " + user.last_name%></p><hr />
      <p>Phone: <%= user.phone_number %></p><hr />
      <p>Email: <%= user.email %></p><hr />
      <p>Address:<br /> <%= user.street_address %><br /><%= user.city + ", " + user.state %><br /><%= user.zipcode %></p><hr />
    </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="user-page-container">
  <div class="connect-image">
    <%= image_tag('GC.png') %>
  </div>
  <hr />
  <div class='new-user-form'>
    <p>Become a new connect team member</p>
  <%= form_for @user do |f|%>
    <%= f.text_field :first_name %>
    <%= f.label "First Name" %><br /><hr />
    <%= f.text_field :last_name %>
    <%= f.label "Last Name" %><br /><hr />
    <%= f.email_field :email %>
    <%= f.label "Email" %><br /><hr />
    <%= f.text_field :phone_number %>
    <%= f.label "Phone" %><br /><hr />
    <%= f.text_field :street_address %>
    <%= f.label :address %><br /><hr />
    <%= f.text_field :city %>
    <%= f.label :city %><br /><hr />
    <%= f.text_field :state %>
    <%= f.label :state %><br /><hr />
    <%= f.text_field :zipcode %>
    <%= f.label :zipcode %><br /><hr />
    <%= f.password_field :password %>
    <%= f.label :password %><br /><hr />
    <%= f.password_field :password_confirmation %>
    <%= f.label "Password Confirmation"%><br /><hr />
    <%= f.submit "Sign Up", class:"create-button" %>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-page-container">
  <div class="connect-image">
    <%= image_tag('GC.png') %>
  </div>
  <hr />
  <div class="user-title">
    <p><%= @user.first_name %>'s <span>Connection</span> Cards</p>
  </div>
  <div class="contact-buttons">
    <div id="uncontacted">Not Contacted</div><div id="contacted">Contacted</div>
  </div><br />
  <% if @cards.empty? %>
    <center><%= image_tag('grey-thank-you.png') %></center><br />
  <% end %>
  <div id="uncontacted-card-holder">
    <% @cards.each do |card| %>
      <% unless card.called? %>
    <div class="assigned-cards">
      <p>Name: <%= card.first_name + " " + card.last_name%></p><hr />
      <p>Phone: <%= card.phone %></p><hr />
      <p>Email: <%= card.email %></p><hr />
      <p>Address:<br /> <%= card.address %><br /><%= card.city + ", " + card.state %><br /><%= card.zipcode %></p><hr />
      <p>Prayer: <%= card.prayer %></p><hr />
      <p>Notes</p>
      <%= form_for [@user, card] do |f| %>
        <%= f.text_area :notes, :rows=>"5", :cols=>"30", value: card.notes, class:"edit-notes" %>
        <%= f.check_box :called %><%= f.label :contacted %><hr />
        <%= f.submit "Update", class:"edit-button" %>
      <% end %>
      <% if card.called? == false %>
      <p>Has Not Been Contacted</p>
      <% else %>
      <p>Has Been Contacted</p>
      <% end %> 
    </div>
      <% end %>
    <% end %>
  </div>
  <div id="contacted-card-holder">
    <% @cards.each do |card| %>
      <% if card.called? %>
    <div class="assigned-cards">
      <p>Name: <%= card.first_name + " " + card.last_name%></p><hr />
      <p>Phone: <%= card.phone %></p><hr />
      <p>Email: <%= card.email %></p><hr />
      <p>Address:<br /> <%= card.address %><br /><%= card.city + ", " + card.state %><br /><%= card.zipcode %></p><hr />
      <p>Prayer: <%= card.prayer %></p><hr />
      <p>Notes</p>
      <%= form_for [@user, card] do |f| %>
        <%= f.text_area :notes, :rows=>"5", :cols=>"30", value: card.notes, class:"edit-notes" %>
        <%= f.check_box :called %><%= f.label :contacted %><hr />
        <%= f.submit "Update", class:"edit-button" %>
      <% end %>
      <% if card.called? == false %>
      <p>Has Not Been Contacted</p>
      <% else %>
      <p>Has Been Contacted</p>
      <% end %>
    </div>
      <% end %>
    <% end %>
  </div>
</div>

<script>
  $('#contacted').click(function(){
    $('#contacted-card-holder').show(function(){
      $('#uncontacted-card-holder').hide();
    });
  });

  $('#uncontacted').click(function(){
    $('#contacted-card-holder').hide(function(){
      $('#uncontacted-card-holder').show();
    });
  });
</script>

app/views/webcards/_left.html.erb
 <div class='new-card-form'>
      <%= @form.text_field :first_name, value: @wcard.first_name%>
      <%= @form.label "First Name"%><br /><hr />
      <%= @form.text_field :last_name, value: @wcard.last_name %>
      <%= @form.label "Last Name" %><br /><hr />
      <%= @form.email_field :email, value: @wcard.email %>
      <%= @form.label "Email" %><br /><hr />
      <%= @form.text_field :phone, value: @wcard.phone %>
      <%= @form.label "Phone" %><br /><hr />
      <%= @form.text_field :address, value: @wcard.address %>
      <%= @form.label :address %><br /><hr />
      <%= @form.text_field :city, value: @wcard.city %>
      <%= @form.label :city %><br /><hr />
      <%= @form.text_field :state, value: @wcard.state %>
      <%= @form.label :state %><br /><hr />
      <%= @form.text_field :zipcode, value: @wcard.zipcode %>
      <%= @form.label :zipcode %><br /><hr />
      <%= @form.text_area :prayer, :rows=>"3", :cols=>"35", value: @wcard.prayer%>
      <%= @form.label "Prayer Request" %><br /><hr />
      <%= @form.text_area :notes, :rows=>"3", :cols=>"35", value: @wcard.notes %>
      <%= @form.label "notes" %><br /><hr />
  </div>

app/views/webcards/_right.html.erb
<div class='all-users-list'>
  <h3><u><b>Assign to:</b></u></h3>
  <% @users.each do |user| %>
  <p><%= @form.radio_button :user_id, user.id %> <%= @form.label :user_id, user.first_name + " " + user.last_name, :value => user.id %></p>
  <% end %>
  <%= @form.submit "Create", class:"create-button" %>
</div>

app/views/webcards/index.html.erb
<div class="webcard-page-container">
  <div class="connect-image">
    <%= image_tag('GC.png') %>
  </div>
  <hr />
<div class="webcard-holder">
  <h2>New Cards From GalleryChurch.com To Assign</h2><hr />
  <ul>
    <% @allwebcards.each do |card| %>
      <li><%= link_to card.first_name + " " + card.last_name, user_webcard_path(@user.id, card.id)%>
        <form action="<%= webcard_path(card.id) %>" method="POST" class="webcard-holder">
        <input type="hidden" name="_method" value="DELETE" />
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
        <button class='deletebutton'>Delete</button></form></li>           
    <% end %>
  </ul>
</div>

app/views/webcards/new.html.erb
<!doctype html>
<header>
  <link href='http://fonts.googleapis.com/css?family=Oxygen:300,400,400italic,500,600,700,700italic&amp;subset=latin,greek-ext,cyrillic,latin-ext,greek,cyrillic-ext,vietnamese' rel='stylesheet' type='text/css' />
</header>

<div class="webcard-page-container">
  <div class="top-header">
    <p>424-888-0995 | <a href="mailto:info@gallerychurch.com">info@gallerychurch.com</a></p>
  </div>

  <div class="webcard-image">
    <%= image_tag 'GreyGCchurch.png' %>
</div>
<div class="webcard-wrapper">
  <h2>Gallery Connect Card<br />
    <span>Tell us about yourself!</span></h2>
    <div class="web-card-form">
      <%= form_for [@card] do |f|%>
      <%= f.text_field :first_name %>
      <%= f.label "First Name" %><br /><hr />
      <%= f.text_field :last_name %>
      <%= f.label "Last Name" %><br /><hr />
      <%= f.email_field :email %>
      <%= f.label "Email" %><br /><hr />
      <%= f.text_field :phone %>
      <%= f.label "Phone" %><br /><hr />
      <%= f.text_field :address %>
      <%= f.label :address %><br /><hr />
      <%= f.text_field :city %>
      <%= f.label :city %><br /><hr />
      <%= f.text_field :state %>
      <%= f.label :state %><br /><hr />
      <%= f.text_field :zipcode %>
      <%= f.label :zipcode %><br /><hr />
      <%= f.text_area :prayer, :rows=>"2", :cols=>"35"%>
      <%= f.label "Prayer Request" %><br /><hr />
      <%= f.text_area :notes, :rows=>"2", :cols=>"35" %>
      <%= f.label "Comments" %><br /><hr />
      <%= f.submit "Submit", class:"create-button", id:"card-submit" %>
      <% end %>
  </div>
</div>
</div>

<div class="confirm-page">
  <div id="dialog" title="Gallery Church">
    <p>Your Connection Card has been received!</p>
  </div>
</div>
 
 
</body>
<script>
$('#card-submit').click(function(){
  $( "#dialog" ).dialog();
});
</script>
</html>

app/views/webcards/show.html.erb
<div class="user-page-container">
  <div class="connect-image">
    <%= image_tag('GC.png') %>
  </div>
  <hr />
    <%= form_for [@user, @webcard] do |f|%>
      <% @form = f %>
      <%= render "left" %>
      <%= render "right" %>
    <% end %>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<div class='coverpage-container'>
  <div class='title-image'>
    <%= image_tag('GC.png') %>
      <%= link_to "Sign Up Here", new_user_path%>
    <hr />
    <div class="login">
        <%= form_tag session_path do%> 
        <%= label_tag "email: " %>
        <%= text_field_tag :email%>
        <%= label_tag "password: " %>
        <%= password_field_tag :password%>
        <%= submit_tag "Login!", class: 'loginbutton' %>
        <% end %>
      </div>  
  </div>
  <div class="flash-message-login">
        <%= raw("<p>#{flash[:message]}</p>") unless flash[:message].nil? %>
  </div>
  <div class='footer-image'>
  </div>
</div>